### ISSUE TITLE
Does not work with Jekyll 3.4.0

### ISSUE THREAD

**Issue by bitboxer** [liaohuqiu/jekyll-multiple-languages#16]
I tried this plugin using jekyll 3.4.0 and I got this error:

```
Gem Load Error is: undefined method `post_read' for class `Jekyll::Document'
Backtrace for gem load error is:
/Users/bodo/.gem/ruby/2.3.1/gems/jekyll-multiple-languages-2.0.3/lib/jekyll-multiple-languages/document.rb:15:in `<class:Document>'
/Users/bodo/.gem/ruby/2.3.1/gems/jekyll-multiple-languages-2.0.3/lib/jekyll-multiple-languages/document.rb:3:in `<module:Jekyll>'
/Users/bodo/.gem/ruby/2.3.1/gems/jekyll-multiple-languages-2.0.3/lib/jekyll-multiple-languages/document.rb:2:in `<top (required)>'
/Users/bodo/.gem/ruby/2.3.1/gems/jekyll-multiple-languages-2.0.3/lib/jekyll-multiple-languages.rb:3:in `require'
/Users/bodo/.gem/ruby/2.3.1/gems/jekyll-multiple-languages-2.0.3/lib/jekyll-multiple-languages.rb:3:in `<top (required)>'
/Users/bodo/.gem/ruby/2.3.1/gems/bundler-1.14.0/lib/bundler/runtime.rb:91:in `require'
/Users/bodo/.gem/ruby/2.3.1/gems/bundler-1.14.0/lib/bundler/runtime.rb:91:in `block (2 levels) in require'
/Users/bodo/.gem/ruby/2.3.1/gems/bundler-1.14.0/lib/bundler/runtime.rb:86:in `each'
/Users/bodo/.gem/ruby/2.3.1/gems/bundler-1.14.0/lib/bundler/runtime.rb:86:in `block in require'
/Users/bodo/.gem/ruby/2.3.1/gems/bundler-1.14.0/lib/bundler/runtime.rb:75:in `each'
/Users/bodo/.gem/ruby/2.3.1/gems/bundler-1.14.0/lib/bundler/runtime.rb:75:in `require'
/Users/bodo/.gem/ruby/2.3.1/gems/bundler-1.14.0/lib/bundler.rb:107:in `require'
/Users/bodo/.gem/ruby/2.3.1/gems/jekyll-3.4.0/lib/jekyll/plugin_manager.rb:37:in `require_from_bundler'
/Users/bodo/.gem/ruby/2.3.1/gems/jekyll-3.4.0/exe/jekyll:9:in `<top (required)>'
```

The api changed a bit. Are you still maintaining this plugin?

**Comment by ashmaroli** [comment]
@bitboxer this has been fixed upstream at Jekyll. You may test by updating your `Gemfile` to point to the `master` branch of `jekyll` till the patch is released.

**Comment by bitboxer** [comment]
Awesome. Thank you!

**Comment by ashmaroli** [comment]
@bitboxer You're welcome. Were you able to test it?

**Comment by bitboxer** [comment]
Yes, worked. And I also found [the commit](https://github.com/jekyll/jekyll/commit/1b1fe27d75c1f4933138b7738a006749d7bba65c) that fixed it 👍

**Comment by ashmaroli** [comment]
Awesome! :smile:
